### ISSUE TITLE
Inconsistent date format recommendations

### ISSUE THREAD

**Issue by sbruder** [LightArrowsEXE/moon_blog#1]
In the blog post [*Kaleido's General Editing Guidelines*](https://lightarrowsexe.github.io/moon_blog/editing-stylesheet/) you state that “Dates should also always use the British date format.” and give the example “December 25th, 1998”. According to the [Wikipedia article on the British date format](https://en.wikipedia.org/wiki/Date_and_time_notation_in_the_United_Kingdom#Date_notation_in_English), however, the British notation for that date is “25 December 1998”.

Is this a mistake in the example or an intentional derivation from British English (like with abbreviated titles)?

**Comment by LightArrowsEXE** [comment]
There are multiple ways of writing out dates in British English, but yeah, the example there currently is not one (although it's a derivation I'd probably make). The correct version should be "The 25th of December, 1998".
